### ISSUE TITLE
Survey Question on the For loop in source file /openmp.c line 45

### ISSUE THREAD

**Issue by pdhung3012** [DragosUnguru/ParallelFrameworksAnalyze#1]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions about this for loop:
1. Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?

2. How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.

3. (Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code and see the optimization of parallelization? Yes/No
- If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).

The for loop is from line 45 of file https:/github.com/DragosUnguru/ParallelFrameworksAnalyze/blob/master//openmp.c
Here is a part of the code:

omp parallel for shared(i,data_in,data_out,no_lines) schedule(static) num_threads(1)
for (i = 0; i < no_lines; ++i)
{
  free(data_in[i]);
  free(data_out[i]);
}

Sincerely thanks

**Comment by DragosUnguru** [comment]
Hi,

I'm happy to help.

1. It is used to embarrassingly parallelize the for loop. It uses a static scheduling as the operations done on the example you've mentioned (simply freeing memory) are in no way unbalanced. The workload is equal across all iterations. As for why I've used the `shared` directive, Its obvious. All the threads operate on the same shared memory that needs to be freed, along, of course, with the for loop index and the array length. There are other parallelized loops throughout the algorithm that may make a greater impact to performance. The memory freeing loop isn't even accounted for when benchmarking results. It is there simply because why not? That's the main attractive point of openMP parallelizing. It's done for you.
2. 5
3. Yes. The input is specified in `input.txt`, where on the first line is the number of lines of text, followed by that many lines of text. E.g.: "3\nIncipit Comoedia Dantis Alagherii\nFlorentini natione non moribus\nThe Divine Comedy". It will output the Burrows-Wheeler encoding of the text, line by line. As for the benchmark results, it heavily depends on the input (very long or short sentences). Some benchmarks can be seen in the project's README.
